name: Compile LaTeX and Release PDF

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 数学教学心理学复习.tex
          latexmk_use_xelatex: true
          docker_image: ghcr.io/xu-cheng/texlive-full:latest
          continue_on_error: false

      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            # LaTeX文档自动构建发布

            此PDF文档由GitHub Actions自动构建并发布。

            发布时间: ${{ github.event.repository.updated_at }}

          draft: false
          prerelease: false
          files: |
            数学教学心理学复习.pdf
