name: Compile LaTeX and Release PDF

on:
  push:
    tags:
      - "v*" # 当推送带有v开头的标签时触发，例如 v1.0, v2.1.3
  workflow_dispatch: # 允许手动触发工作流程

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 获取完整的历史记录，确保所有资源都可用

      - name: Cache LaTeX packages
        uses: actions/cache@v3
        with:
          path: /tmp/texlive
          key: texlive-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            texlive-

      - name: Setup TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: elegantbook-cn.tex
          latexmk_use_xelatex: true
          extra_system_packages: |
            texlive-xetex
            texlive-fonts-extra
            texlive-lang-chinese
            texlive-science
          pre_compile: |
            # 设置所有文件的权限为777，确保编译过程中没有权限问题
            chmod -R 777 .

      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            elegantbook-cn.pdf
